import Link from "next/link";
import { ArrowRight, ArrowUpRight, BookOpen, CircleHelp, Database, FlaskConical, ShieldCheck, Wallet } from "lucide-react";
import "./docs.css";

const steps = [
  { icon: FlaskConical, title: "Create a market", body: "Choose a model name, an accuracy target from 0 to 100%, and a future deadline. Kally deploys one intelligent contract per market on GenLayer Studio Dev." },
  { icon: Wallet, title: "Fund and participate", body: "The creator funds a GEN bond. Participants then place YES or NO positions before the deadline. Studio Dev GEN is testnet currency." },
  { icon: Database, title: "Submit evidence", body: "The model owner submits a checkpoint CID. A benchmark report containing predictions is uploaded to IPFS and passed to the contract for resolution." },
  { icon: ShieldCheck, title: "Resolve and claim", body: "GenLayer validators check the report and score its predictions. The result settles the market; eligible participants claim their payouts on-chain." },
];

export default function Docs() {
  return <main className="docs-page">
    <header className="site-header wrap"><Link href="/" className="brand"><img className="brand-logo" src="/kally-logo.png" alt=""/><span>Kally<span className="brand-dot">.</span></span></Link><nav><Link href="/">Home</Link><Link href="/markets">Markets</Link><Link href="/docs" aria-current="page">Docs</Link></nav><Link href="/markets" className="header-cta">Launch app <ArrowUpRight size={17}/></Link></header>
    <div className="docs-hero"><div className="wrap"><p className="eyebrow light">KALLY DOCUMENTATION / STUDIO DEV</p><h1>Clear markets.<br/><em>Verifiable outcomes.</em></h1><p>Everything you need to understand Kally&apos;s current testnet prototype, from your first position to a resolved benchmark.</p><Link href="/markets" className="button button-lime">Explore markets <ArrowRight size={17}/></Link></div></div>
    <div className="docs-layout wrap"><aside className="docs-nav"><span>ON THIS PAGE</span><a href="#overview">Overview</a><a href="#workflow">How it works</a><a href="#rules">Market rules</a><a href="#evidence">Evidence & scoring</a><a href="#limits">Current limitations</a><a href="#roadmap">Roadmap</a><a href="#faq">FAQ</a></aside><div className="docs-body">
      <section id="overview"><div className="docs-kicker"><BookOpen size={17}/> START HERE</div><h2>What is Kally?</h2><p>Kally is a prediction market prototype for measurable AI benchmark outcomes. Each market asks whether a named model will reach a target accuracy score by a deadline. Market state and payouts live in a GenLayer intelligent contract on the Studio Dev testnet.</p><div className="docs-callout"><strong>Development network</strong><span>Use a test wallet and test GEN. Contracts and network behavior may change during development.</span></div></section>
      <section id="workflow"><div className="docs-kicker">01 / WORKFLOW</div><h2>From question to settlement</h2><div className="docs-steps">{steps.map((step, i) => <article key={step.title}><div className="docs-step-icon"><step.icon size={20}/></div><div><small>STEP {String(i+1).padStart(2,"0")}</small><h3>{step.title}</h3><p>{step.body}</p></div></article>)}</div></section>
      <section id="rules"><div className="docs-kicker">02 / MARKET RULES</div><h2>Know the terms before you bet</h2><div className="docs-rule-grid"><div><span>METRIC</span><strong>Accuracy</strong><p>Correct predictions divided by scored examples, expressed as a percentage.</p></div><div><span>DATASET</span><strong>kally-demo-v1</strong><p>A small classification demo dataset used by the current implementation.</p></div><div><span>TARGET</span><strong>0–100%</strong><p>The market resolves YES when the verified score is at least the target.</p></div><div><span>STAKE</span><strong>Test GEN</strong><p>The creator bond and YES/NO positions are held by the market contract.</p></div></div><p>The creator must fund a bond before bets are accepted. Once resolved, winning participants claim their share of the pool. If the target is missed, the contract makes the creator bond claimable by the resolver according to its rules. Inspect the contract before interacting.</p></section>
      <section id="evidence"><div className="docs-kicker">03 / EVIDENCE</div><h2>How scores are produced</h2><p>Reports are content-addressed with IPFS CIDs. At resolution, the contract requests a report from its configured HTTPS gateway and checks its market metadata, and recomputes accuracy from ten submitted predictions against the fixed demo labels. GenLayer validators reach consensus on the resulting score before state changes become final.</p><div className="docs-callout"><strong>What the current demo actually runs</strong><span>It scores submitted predictions. It does not download or execute arbitrary model checkpoints, Docker images, GLUE, or ImageNet. A checkpoint CID is recorded as metadata for traceability.</span></div><p>You can inspect the market contract source in the <a href="https://github.com/linoxbt/kally/blob/main/contracts/KallyMarket.py" target="_blank" rel="noreferrer">Kally repository</a> and review transaction state in the Studio Dev explorer when an address is available.</p></section>
      <section id="limits"><div className="docs-kicker">04 / STATUS</div><h2>Prototype boundaries</h2><ul><li>Markets are imported by contract address and stored in your browser; there is no global market index yet.</li><li>Benchmark uploads require the separate Kally uploader service and a configured IPFS node.</li><li>Outcomes depend on the exact market code and report data. This is testnet software, not a production betting service.</li></ul></section>
      <section id="roadmap"><div className="docs-kicker">05 / ROADMAP</div><h2>Three useful next pages</h2><ul><li><strong>Benchmark runs:</strong> show checkpoint provenance, dataset version, runner logs, and reproducible score evidence.</li><li><strong>Market history:</strong> index every deployment, trade, resolution, cancellation, and claim across wallets.</li><li><strong>Creator console:</strong> manage model submissions, bond status, deadlines, and benchmark readiness.</li></ul></section>
      <section id="faq"><div className="docs-kicker"><CircleHelp size={16}/> FREQUENTLY ASKED</div><h2>Questions, answered</h2><details><summary>Which wallet do I need?</summary><p>Kally uses Reown AppKit to connect compatible EVM wallets. Switch to GenLayer Studio Dev (chain ID 61997) before signing a transaction.</p></details><details><summary>Where do I find my market?</summary><p>Use its contract address in the “Have a market address?” field on the Markets page. Imported addresses are saved in your browser.</p></details><details><summary>When can I claim?</summary><p>After the market resolves or cancels, the contract determines whether your position has a claimable payout. Use “Claim payout” on the market detail panel.</p></details></section>
      <div className="docs-end"><h2>Ready to explore?</h2><p>Review the terms of a market, then take a position with your test wallet.</p><Link href="/markets" className="button button-lime">Open Kally <ArrowUpRight size={17}/></Link></div>
    </div></div>
    <footer className="footer wrap"><Link href="/" className="brand"><img className="brand-logo" src="/kally-logo.png" alt=""/><span>Kally<span className="brand-dot">.</span></span></Link><span>GenLayer Studio Dev testnet</span><Link href="/markets">Explore markets <ArrowUpRight size={14}/></Link></footer>
  </main>;
}
